untitled/first_app/urls.py
from django.conf.urls import url
from first_app import views

#template tagging
app_name = 'first_app'

urlpatterns = [
    url(r'^$', views.indexx, name='indexx'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^relative/$',views.relative, name='relative'),
    url(r'^other/$',views.other, name='other'),
]

untitled/untitled/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from first_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^first_app/', include('first_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'^special/$', views.special, name='special'),
]

untitled/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic)
    name = models.CharField(max_length=200, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    #additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

untitled/first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

untitled/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from first_app.models import Topic, AccessRecord, Webpage
from first_app.forms import UserForm, UserProfileInfoForm
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records' : webpages_list}
    return render(request, 'first_app/index.html', context=date_dict)

def other(request):
    context_dict = {'text':'hello world','number':100}
    return render(request, 'first_app/other.html', context_dict)

def relative(request):
    return render(request, 'first_app/relative.html')

def indexx(request):
    return render(request, 'first_app/indexx.html')

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'first_app/registration.html', {
                                                            'user_form':user_form,
                                                            'profile_form':profile_form,
                                                            'registered':registered
                                                           })

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('first_app:indexx'))
            else:
                return HttpResponse("<h2>Account not active</h2>")

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and Password: {}".format(username,password))
            return HttpResponse("<h2>Invalid login details supplied!</h2>")

    else:
        return render(request, 'first_app/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('first_app:indexx'))

@login_required
def special(request):
    return HttpResponse("<h2>Only if logged in you can see the page</h2>")

untitled/templates/first_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="shortcut icon" href="{% static "images/favicon.ico" %}" type="image/x-icon" />
    <title>{% block title_block %}base{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-inverse navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}" class="navbar-brand">Brand</a></li>
                <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
                <li><a href="{% url 'first_app:other' %}" class="navbar-link">Other</a></li>
                <li><a href="{% url 'first_app:register' %}" class="navbar-link">Register</a></li>
            </ul>

            <ul class="nav navbar-right navbar-nav">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}" class="navbar-link">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'first_app:user_login' %}" class="navbar-link">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>


    <div class="container">
        {% block body_block %}
        <!-- anything outside will be inherited -->
        {% endblock %}
    </div>
</body>
</html>

untitled/templates/first_app/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>First App</title>
    <link rel="shortcut icon" href="{% static "images/favicon.ico" %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}" />

</head>
<body>

    <h1>JUST A LOGO <img src="{% static "images/Accelrys.jpg" %}" alt="Not loading" width="3%" height="3%"></h1>
    <h1>Hello there from template/first_app/index.html</h1>
    <h2>Here are your access records:</h2>
    <div class="djangotwo">
        {% if access_records %}
        <table>
            <thead>
                <th>Site name:</th>
                <th>Date accessed:</th>
            </thead>
            <tbody>
                {% for acc in access_records %}
                <tr>
                    <td>{{ acc.name }}</td>
                    <td>{{ acc.date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No access reords found!</p>
        {% endif %}

    </div>

</body>
</html>

untitled/templates/first_app/indexx.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}

{% block title_block %}Index Page{% endblock %}

{% block body_block %}

    <div class="jumbotron">
        <h1>Django level 5</h1>
    </div>

{% endblock %}

untitled/templates/first_app/login.html
{%  extends 'first_app/base.html' %}
{% block title_block %}Login Here{% endblock %}

{% block body_block %}

    <div class="jumbotron">
        <h1>Please Login:</h1>
        <form method="post" action="{% url 'first_app:user_login' %}">

            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="enter username">

            <label for="password">Password:</label>
            <input type="password" placeholder="enter password" name="password">

            <input name="" value="Login" type="submit">

        </form>
    </div>

{% endblock %}

untitled/templates/first_app/other.html
<!DOCTYPE html>

{% extends "first_app/base.html" %}
{% block title_block %}other{% endblock %}
    {% block body_block %}
        <h1>Welcome to other</h1>

        <h3>{{ text|upper }} - {{ number|add:"99" }}</h3>  <!-- upper is a filter that uppercase all letters and add, adds number + whatever is the argument ie 99 here-->
        <h4>{{ text|cut:"hell" }}</h4>
    {% endblock %}

untitled/templates/first_app/registration.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block title_block %}Register{% endblock %}

{% block body_block %}

    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering</h1>
        {% else %}
            <h1>Register here:</h1>
            <h3>Fill out the form:</h3>

            <form enctype="multipart/form-data" method="post" action="">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="Register">
            </form>

        {% endif %}
    </div>

{% endblock %}

untitled/templates/first_app/relative.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>relative</title>
</head>
<body>
    <h1>WElcome to relative</h1>
    <a href="{% url 'first_app:other' %}">The other page</a> {# make sure there is no gap in quotes #}
    <a href="{% url 'admin:index' %}">Admin page</a>
    <a href="{% url 'index' %}">Link to index</a>

</body>
</html>